import Head from "next/head";
import Image from "next/image";
import '../styles/globals.css';

export const metadata = {
  title: 'Range Component',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
    <title>Range Component</title>
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <body>
      <header style={{ position: 'fixed', top: 0, right: 0, padding: '10px' }}>
        <Image className='logo' src="./logo.svg" alt="Logo" width={120} height={50} />
      </header>
      {children}
      </body>
    </html>
  )
}
